# Shell variables
# Generated by 'wal'
wallpaper='/home/defaultuser/.config/wpg/wallpapers/z84MteZ.png'

# Special
background='#150e14'
foreground='#fffdf8'
cursor='#e9e2de'

# Colors
color0='#150e14'
color1='#DA4F4F'
color2='#D76567'
color3='#9B837B'
color4='#B8A59C'
color5='#C6B3A9'
color6='#D7C8B8'
color7='#e9e2de'
color8='#2d1d2b'
color9='#ff5353'
color10='#ff6e72'
color11='#dba18d'
color12='#ffceb4'
color13='#ffe1c3'
color14='#ffffd1'
color15='#fffdf8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
