source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "Delapouite/kakoune-buffers"
plug "alexherbo2/auto-pairs.kak"

hook global InsertCompletionShow .* %{
	try %{
		exec -draft 'h<a-K>\h<ret>'
		map window insert <s-tab> <c-p>
		map window insert <tab> <c-n>
	}
}

hook global InsertCompletionHide .* %{
        unmap window insert <tab> <c-n>
            unmap window insert <s-tab> <c-p>
}

add-highlighter global/ number-lines
set global tabstop 4
set global indentwidth 4

evaluate-commands %sh{
    selection="rgb:373b41"
    window="rgb:383838"
    text="rgb:D8D8D8"
    text_light="rgb:4E4E4E"
    line="rgb:282a2e"
    comment="rgb:969896"
    red="rgb:cc6666"
    orange="rgb:d88860"
    yellow="rgb:f0c674"
    green="rgb:b5bd68"
    green_dark="rgb:a1b56c"
    blue="rgb:81a2be"
    aqua="rgb:87afaf"
    magenta="rgb:ab4642"
    purple="rgb:b294bb"
    echo "
        face global MenuForeground ${text_light},blue
        face global MenuBackground ${aqua},${window}
        face global MenuInfo ${aqua}
        face global Information white,${window}
        face global Error white,${red}
        face global StatusLine ${text},${window}
        face global StatusLineMode ${yellow}+b
        face global StatusLineInfo ${aqua}
        face global StatusLineValue ${green_dark}
        face global StatusCursor ${window},${aqua}
        face global Whitespace ${text_light}+f
        face global PrimarySelection default,${selection}+fg
        face global SecondarySelection default,${selection}+fg
        face global PrimaryCursor black,${aqua}+fg
		face global SecondaryCursor black,${aqua}+fg
    "
}
